services:
  - type: web
    name: score-sync-backend
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: cd backend && gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://scoresync_cf1c_user:V4yTJhpzCd7X6A2JxEwD2sUH1alvYJtw@dpg-d0lm403e5dus73cncus0-a.oregon-postgres.render.com/scoresync_cf1c
      - key: FIREBASE_STORAGE_BUCKET
        value: scoresync-3ce4c.appspot.com
      - key: FIREBASE_WEB_API_KEY
        value: AIzaSyDM4P96ZUTRn-unirz1fZVRPJNByMAWdAc
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://score-sync.vercel.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://score-sync.vercel.app
      - key: DEBUG
        value: false
    healthCheckPath: /api/health/
    autoDeploy: true

databases:
  - name: score-sync-db
    databaseName: scoresync_cf1c
    user: scoresync_cf1c_user
    plan: free
